// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNu10dvjXRA8TddefUhnbHuE_A6Ol6Bf4',
    appId: '1:431868831516:web:794166120b61e27b727cd9',
    messagingSenderId: '431868831516',
    projectId: 'stridely-34510',
    authDomain: 'stridely-34510.firebaseapp.com',
    storageBucket: 'stridely-34510.firebasestorage.app',
    measurementId: 'G-GKD3PRJ8PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmL_BgoMBpv6UORZ8lsDIRJ4VtLd8le48',
    appId: '1:431868831516:android:c0ad46fb68bf6ce6727cd9',
    messagingSenderId: '431868831516',
    projectId: 'stridely-34510',
    storageBucket: 'stridely-34510.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHDOnqfx3nILn6zRHaJSGvOQJRFaoq8DI',
    appId: '1:431868831516:ios:43edb4d873154985727cd9',
    messagingSenderId: '431868831516',
    projectId: 'stridely-34510',
    storageBucket: 'stridely-34510.firebasestorage.app',
    androidClientId: '431868831516-kj0emgghvd7k931qh5namspsnuk01ifs.apps.googleusercontent.com',
    iosClientId: '431868831516-g1ivsgqvsjlnchi954btuhhk5dms6oi0.apps.googleusercontent.com',
    iosBundleId: 'com.ajaysingh.stridely',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHDOnqfx3nILn6zRHaJSGvOQJRFaoq8DI',
    appId: '1:431868831516:ios:7909f01502acf556727cd9',
    messagingSenderId: '431868831516',
    projectId: 'stridely-34510',
    storageBucket: 'stridely-34510.firebasestorage.app',
    androidClientId: '431868831516-kj0emgghvd7k931qh5namspsnuk01ifs.apps.googleusercontent.com',
    iosClientId: '431868831516-vfsl1idejk9lcds0novgohl139cga8ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNu10dvjXRA8TddefUhnbHuE_A6Ol6Bf4',
    appId: '1:431868831516:web:c00011c2a8d15686727cd9',
    messagingSenderId: '431868831516',
    projectId: 'stridely-34510',
    authDomain: 'stridely-34510.firebaseapp.com',
    storageBucket: 'stridely-34510.firebasestorage.app',
    measurementId: 'G-SPQQGR8PM2',
  );
}
